---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: Relationship between socioeconomic variables
draft: false
image: Gapminder.jpg
keywords: ""
slug: Socioeconomic
title: Correlation analysis
---



<div id="let-us-revisit-the-gapminder-database" class="section level1">
<h1>Let us revisit the Gapminder database</h1>
<p>In this section, we will use data frames from the worldbank in order analyze the relationships among the following socioeconomic variables:</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$</li>
<li>Female fertility: The number of babies per woman</li>
<li>Primary school enrollment as % of children attending primary school</li>
<li>Mortality rate, for under 5, per 1000 live births</li>
<li>HIV prevalence : The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)



worldbank_data &lt;-  read_csv(here::here(&quot;data&quot;,&quot;worldbank_data.csv&quot;))

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  read.csv(here::here(&quot;data&quot;,&quot;countries.csv&quot;))</code></pre>
<p>We will work with 3 data frames:</p>
<ul>
<li>hiv</li>
<li>life_expectancy</li>
<li>worldbank_data</li>
</ul>
<p>We can see that hiv and life_expectancy are messy, since they contain values instead of variables in their columns. Since worldbank_data is tidy, it makes sense to tidy the data in order to manipulate it better in our analyses.</p>
<pre class="r"><code>#glimpse(hiv)
#glimpse(life_expectancy)
#glimpse(worldbank_data)</code></pre>
<p>Notice the period of observations within each data frame:</p>
<ul>
<li>hiv : 1979 to 2011</li>
<li>life_expectancy : 1800 to 2064</li>
<li>worldbank_data : 1960 to 2016</li>
</ul>
<p>Since we are going to study correlations and relationships between these data frames, it makes sense to join the tables and to keep the period between 1960 to 2016.</p>
<pre class="r"><code>#First, we tidy the data
hiv_pivot &lt;- hiv %&gt;%
  pivot_longer(cols = c(&quot;1979&quot;:&quot;2011&quot;),
               names_to = &quot;date&quot; , 
               values_to = &quot;hiv_prevalence&quot;, 
               values_drop_na= FALSE)


life_expectancy_pivot &lt;- life_expectancy %&gt;%
  pivot_longer(cols = c(&quot;1800&quot;:&quot;2100&quot;),
   names_to = &quot;date&quot; , 
   values_to = &quot;life_expectancy&quot;, 
   values_drop_na= FALSE)


#We convert date into a double in order to perform the left join
life_expectancy_pivot$date &lt;- as.double(life_expectancy_pivot$date)
hiv_pivot$date &lt;- as.double(hiv_pivot$date)
#Left join the three data frames
hiv_life_wb &lt;- left_join(worldbank_data,life_expectancy_pivot) %&gt;%
  left_join(.,hiv_pivot) %&gt;%
#Add a region column, using the countrycode package
  mutate(region= countrycode(sourcevar = country, origin = &quot;country.name&quot;,destination = &quot;region&quot;))</code></pre>
<div id="the-relation-between-hiv-prevalence-and-life-expectancy" class="section level2">
<h2>The relation between HIV prevalence and life expectancy</h2>
<p>Let us study the relation between HIV prevalence and life expectancy</p>
<pre class="r"><code>ggplot(hiv_life_wb,aes(x=hiv_prevalence,y=life_expectancy)) +
  geom_smooth() +
  geom_point(alpha=0.2)+
  labs(title=&quot;HIV prevalence is negatively correlated with life expectancy&quot;,subtitle=&quot;Relationship between HIV prevalence and life expectancy&quot;,x=&quot;HIV prevalence (aged 15 to 49)&quot;,y=&quot;Life expectancy&quot;) +
  theme_bw()</code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-3-1.png" width="624" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(hiv_life_wb,aes(x=hiv_prevalence,y=life_expectancy)) +
  geom_smooth(method=&quot;gam&quot;) +
  geom_point(alpha=0.2)+
  labs(title=&quot;Relationship between HIV prevalence and life expectancy by region&quot;,subtitle=&quot;The relationship is not obvious in all regions!&quot;,x=&quot;HIV prevalence (aged 15 to 49)&quot;,y=&quot;Life expectancy&quot;) +
  theme_bw() +
  facet_wrap(~region,scales=&quot;free&quot;)</code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-4-1.png" width="624" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#We clean the NAs within our data frame in order to calculate the correlation coefficient
hiv_life_wb_cleaned &lt;- na.omit(hiv_life_wb)
cor(hiv_life_wb_cleaned$hiv_prevalence,hiv_life_wb_cleaned$life_expectancy)</code></pre>
<pre><code>## [1] -0.585</code></pre>
<blockquote>
<p>Overall, HIV prevalence and life expectancy are negatively correlated (ρ=-0.585) However, this may not be a direct causal effect, as HIV prevalence might be strongly correlated with bad sanitary conditions and other diseases. This is further shown in the facetted scatterplots : the relationship seems clear in regions like Sub-Saharan Africa, but is less obvious in East Asia &amp; Pacific, indicating that other variables need to be taken into account.</p>
</blockquote>
</div>
<div id="the-relationship-between-fertility-rate-and-gdp-per-capita" class="section level2">
<h2>The relationship between fertility rate and GDP per capita</h2>
<pre class="r"><code>ggplot(hiv_life_wb,aes(x=NY.GDP.PCAP.KD,y=SP.DYN.TFRT.IN)) +
  geom_point(alpha=0.2,size=0.5)+
  geom_smooth(method=&quot;lm&quot;) +
  labs(title=&quot;High socioeconomic classes have better access to contraception&quot;,subtitle=&quot;Relationship between GDP per capita and fertility rate in each region&quot;,x=&quot;GDP per capita&quot;,y=&quot;Fertility rate&quot;) +
  theme_bw()+
  facet_wrap(~region,scales=&quot;free&quot;)</code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-5-1.png" width="624" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Calculate the correlation coefficient
cor(hiv_life_wb_cleaned$NY.GDP.PCAP.KD,hiv_life_wb_cleaned$SP.DYN.TFRT.IN)</code></pre>
<pre><code>## [1] -0.463</code></pre>
<blockquote>
<p>Fertility and GDP per capita are negatively correlated, mainly in the poorest regions such as Sub-Saharan Africa and South Asia, which display the steepest slopes. One interpretation would be that higher socio-economic classes tend to have better access to healthcare and can afford contraceptives. Moreover, the correlation coefficient between the two variables is -0.463, which further proves this relationship.</p>
</blockquote>
</div>
<div id="in-relative-terms-east-asia-pacific-is-the-region-that-most-misses-hiv-data" class="section level2">
<h2>In relative terms, East Asia &amp; Pacific is the region that most misses HIV data</h2>
<p>Data may be missing in some countries,so we will check which regions have the most observations with missing data, mainly for the HIV variable.</p>
<p>We will conduct the following analysis in absolute and relative terms :</p>
<pre class="r"><code>#Filter years between 1979 and 2011 to avoid unnecessary NAs since HIV data is only available within this time frame.
hiv_missing &lt;- hiv_life_wb %&gt;%
  group_by(region) %&gt;%
  filter(date&gt;=1979) %&gt;%
  filter(date&lt;=2011)  %&gt;%
##Calulate the absolute number of missing data and the proportion relative to the number of cells.
  summarize(hiv_na = sum(is.na(hiv_prevalence)),proportion= round(hiv_na/n(),digits=3)) %&gt;%
  arrange(desc(hiv_na))

#Plot of absolute values
ggplot(hiv_missing,aes(x=reorder(region,hiv_na),y=hiv_na)) + 
  geom_col(fill=&quot;steelblue&quot;) + 
  theme_bw() +
  coord_flip() +
  labs(title=&quot;Europe &amp; Central Asia is the region that most misses HIV data&quot;,subtitle=&quot;Number of missing HIV prevalence observations per region&quot;, y=&quot;HIV missing data&quot;,x=&quot;&quot;)  +
  geom_text(aes(label=hiv_na), vjust=0.5,hjust=1.5,angle=0, color=&quot;white&quot;, size=4)</code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-6-1.png" width="624" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Plot of proportion 
ggplot(hiv_missing,aes(x=reorder(region,proportion),y=proportion)) + 
  geom_col(fill=&quot;steelblue&quot;) + 
  theme_bw() +
  coord_flip() +
  labs(title=&quot;In relative terms, East Asia &amp; Pacific is the region\nthat most misses HIV data&quot;,subtitle=&quot;Proportion of missing HIV prevalence observations per region&quot;,y=&quot;HIV missing data&quot;,x=&quot;&quot;)  +
  geom_text(aes(label=scales::percent(proportion)), vjust=0.5,hjust=1.5,angle=0, color=&quot;white&quot;, size=4) </code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-6-2.png" width="624" style="display: block; margin: auto;" /></p>
<blockquote>
<p>The region that most lacks HIV data is Europe &amp; Central Asia. However, it is more relevant to compare missing data with the number of values within the data frame, since regions do not have the same number of countries. The second analysis indicates that the region with the greatest missing HIV data is East Asia &amp; Pacific (74.1% of missing data)</p>
</blockquote>
</div>
<div id="top-5-countries-with-the-greatestlowest-decrease-in-mortality-rate-per-region" class="section level2">
<h2>Top 5 countries with the greatest/lowest decrease in mortality rate per region</h2>
<p>Under-five mortality is a big concern, especially in the poorest regions of the world. Thus, it would be relevant to study its evolution between 1960 and 2016 for each region. We will find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration. Note that to have a logical comparison, countries that do not have data in 1960 or in 2016 will not be displayed.</p>
<pre class="r"><code>#We filter the data between 1960 (initial year) and 2016 (final year) and we untidy it
intermediary &lt;- hiv_life_wb %&gt;%
                select(c(&quot;country&quot;,&quot;region&quot;,&quot;date&quot;,&quot;SH.DYN.MORT&quot;)) %&gt;% 
                filter(date== &quot;1960&quot;| date==&quot;2016&quot;) %&gt;%
                pivot_wider(names_from=&quot;date&quot;, values_from=&quot;SH.DYN.MORT&quot;)
         
colnames(intermediary) = c(&quot;country&quot;,&quot;region&quot;,&quot;initial&quot;,&quot;final&quot;)

intermediarytwo &lt;- intermediary %&gt;% 
mutate(rate_of_change=(final-initial)/initial) %&gt;% #We create a delta column, representing the rate of change
group_by(region) %&gt;%
summarize(country,rate_of_change) %&gt;%
arrange(region,desc(rate_of_change))


#We filter the top 5 per region
top_five &lt;- intermediarytwo %&gt;%
            slice_min(order_by= rate_of_change,n=5) %&gt;%
            summarize(country,rate_of_change)

ggplot(top_five,aes(x=reorder(country,rate_of_change),y=abs(rate_of_change))) +
  geom_col(fill=&quot;steelblue&quot;) + coord_flip()+ facet_wrap(~region,scales=&quot;free&quot;) + 
  labs(title=&quot;South Korea has had the greatest decrease in mortality rate over the last 50 years &quot;,subtitle=&quot;Top 5 countries with the greatest decrease in mortality rate per region &quot;,y=&quot;Change in mortality rate between 1960 and 2016&quot;,x=&quot;&quot;) +
  geom_text(aes(label=scales::percent(rate_of_change)), vjust=1,hjust=1,angle=0, color=&quot;white&quot;, size=3) </code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-7-1.png" width="1152" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#We filter the bottom 5 per region
bottom_five &lt;- intermediarytwo %&gt;%
    slice_max(order_by= rate_of_change,n=5) %&gt;%
  summarize(country,rate_of_change)


ggplot(bottom_five,aes(x=reorder(country,rate_of_change),y=abs(rate_of_change))) + geom_col(fill=&quot;steelblue&quot;) + coord_flip()+ facet_wrap(~region,scales=&quot;free&quot;) + labs(title=&quot;Lesotho has had the worst decrease in mortality rate over the last 50 years&quot;,y=&quot;Change in mortality rate between 1960 and 2016&quot;,subtitle=&quot;Top 5 countries with the lowest decrease in mortality rate per region&quot;,x=&quot;&quot;) +geom_text(aes(label=scales::percent(rate_of_change)), vjust=1,hjust=1,angle=0, color=&quot;white&quot;, size=3) </code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-7-2.png" width="1152" style="display: block; margin: auto;" /></p>
<blockquote>
<p>It is worth mentioning the main limit of this analysis : the most advanced countries had the lowest margin of improvement. Thus, it is not very surprising to see France in the 5 countries that have evolved the least between 1960 and 2016. Moreover, as we said earlier, many countries do not have data for this specific time frame, which may generate a bias in the study. Taking the first and the last available data for each country could have been a solution, but it would have generated another bias since the years of comparison would be different for each country. Furthermore, there may be duplicates within regions when the amount of countries with available data is smaller than five, such as in North America.</p>
</blockquote>
</div>
<div id="relationship-between-primary-school-enrollment-and-fertility-rate" class="section level2">
<h2>Relationship between primary school enrollment and fertility rate</h2>
<p>Finally, a last interesting analysis would be to study the relationship between primary school enrollment and fertility rate.</p>
<pre class="r"><code>ggplot(hiv_life_wb,aes(x=SE.PRM.NENR,y=SP.DYN.TFRT.IN)) +
  geom_smooth() +
  geom_point(alpha=0.2)+
  labs(title=&quot;Large families have way smaller primary school enrollment rates&quot;,subtitle=&quot;Relationship between primary school enrollment and fertility rate&quot;,x=&quot;Primary school enrollment&quot;,y=&quot;Fertility rate&quot;) +
  theme_bw()+
  facet_wrap(~region,scales=&quot;free&quot;)</code></pre>
<p><img src="/blogs/Socioeconomic_files/figure-html/unnamed-chunk-8-1.png" width="624" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#We calculate the correlation coefficient
cor(hiv_life_wb_cleaned$SE.PRM.NENR,hiv_life_wb_cleaned$SP.DYN.TFRT.IN)</code></pre>
<pre><code>## [1] -0.793</code></pre>
<blockquote>
<p>There seems to be a very clear negative correlation between primary school enrollment and fertility rate for all regions ((ρ=-0.793). We have seen previously that GDP per capita and fertility rate were negatively correlated. Thus, the poorest families tend to have more children. These children may not have access to education due to financial restrictions or may even be constrained to work instead of attending school. This is usually the case in rural areas, and it would be relevant to further analyze the link between the % of rural population and fertility.</p>
</blockquote>
</div>
</div>
